# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regda.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class RegDa(object):
    def reda(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(184, 103)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.RegClose = QtWidgets.QPushButton(Dialog)
        self.RegClose.setGeometry(QtCore.QRect(50, 70, 75, 23))
        self.RegClose.setObjectName("RegClose")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "УСПЕШНО"))
        self.RegClose.setText(_translate("Dialog", "OK"))
